package states;

public enum ContainerState {
    INITIALIZATION,
    PREPARATION,
    WAITING,
    FIND_LOAD_POSITION,
    MOVE_TO_LOAD_POSITION,
    LOAD,
    FIND_UNLOAD_POSITION,
    MOVE_TO_UNLOAD_POSITION,
    UNLOAD,
    END
}
